spring:
  cloud:
    stream:
      bindings:
        input:
          destination: user-details
          group: usage-cost-consumer
        output:
          destination: usage-cost
          producer:
            requiredGroups:
              - logger
