apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springioguides-springbootkubernetes-demo
  name: springioguides-springbootkubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springioguides-springbootkubernetes-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springioguides-springbootkubernetes-demo
    spec:
      containers:
      - image: springguides/demo
        name: springioguides-springbootkubernetes-demo
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springioguides-springbootkubernetes-demo
  name: springioguides-springbootkubernetes-demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springioguides-springbootkubernetes-demo
  type: ClusterIP
status:
  loadBalancer: {}
